### ISSUE TITLE
HKActivitySummaryQuery is missing

### ISSUE THREAD

**Issue by kuglee** [PromiseKit/HealthKit#2]
Please add HKActivitySummaryQuery to the extension.

HKActivitySummaryQuery:

- init(predicate: NSPredicate?, resultsHandler handler: @escaping (HKActivitySummaryQuery, [HKActivitySummary]?, Error?) -> Void)

Thank you!

**Comment by mxcl** [comment]
Merged, I will publish a new version of PromiseKit now and a new version here.

If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).

**Comment by kuglee** [comment]
Thanks! Donated 🙂

**Comment by mxcl** [comment]
Many thanks!

**Comment by mxcl** [comment]
The 6.6.1 pod is now live.

**Comment by kuglee** [comment]
Thanks! 👍
